version: "0.1.0"
services:
  backend:
    image: "backend:${TAG-latest}"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: mvn spring-boot:run
    depends_on:
      - db
    environment:  # 添加环境变量
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/discount_card?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      # 本地开发修改此处
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: test_pass
    ports:
      - "8081:8081"
  frontend:
    image: "frontend:${TAG-latest}"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "20000:3000"
    volumes:
      - ./frontend:/src/app
      - /src/app/node_modules
    command: ["pnpm", "dev"]
  admin:
    image: "admin:${TAG-latest}"
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - "20001:8000"
    volumes:
      - ./admin:/src/app
      - /src/app/node_modules
    command: ["pnpm", "dev"]
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: discount_card
      # 本地开发修改此处
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - 3307:3306
    volumes:
      - discount_card_db_data:/var/lib/mysql

volumes:
  discount_card_db_data:
