version: "0.1.0"
services:
  backend:
    image: "backend:${TAG-latest}"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["tail", "-f", "/dev/null"]
  frontend:
    image: "frontend:${TAG-latest}"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "20000:3000"
    volumes:
      - ./frontend:/src/app
      - /src/app/node_modules
    command: ["pnpm", "dev"]
  admin:
    image: "admin:${TAG-latest}"
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    command: ["tail", "-f", "/dev/null"]
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: discount_card
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - 3306:3306
    volumes:
      - discount_card_db_data:/var/lib/mysql

volumes:
  discount_card_db_data:
