# Use an official Node runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /src/app

# Copy package.json and pnpm-lock.yaml
COPY package.json ./
COPY pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm
RUN pnpm install

# Bundle app source
COPY . .

# Make port 80 available to the world outside this container
EXPOSE 3000

# Define the command to run your app
CMD [ "pnpm", "dev" ]
