[project]
name = ""
version = ""
description = ""
authors = [
    {name = "allenyuchen", email = "allenyuchen@hotmail.com"},
]
dependencies = [
    "fastapi>=0.103.1",
    "uvicorn>=0.23.2",
    "black>=23.9.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

